Brigand: test/real.cpp File Reference
real.cpp File Reference
#include <brigand/types/real.hpp>
#include <cassert>
#include <limits>
#include <iostream>
Typedefs
using single_zero = brigand::single_< 0x00000000U >
using single_one = brigand::single_< 0x3F800000U >
using single_nan = brigand::single_< 0xFFFFFFFFU >
using double_zero = brigand::double_< 0x0000000000000000ULL >
using double_one = brigand::double_< 0x3FF0000000000000ULL >
using double_nan = brigand::double_< 0xFFFFFFFFFFFFFFFFULL >
Functions
template<typename T >
bool is_nan (T v)
void real_test ()
Typedef Documentation
using double_nan = brigand::double_<0xFFFFFFFFFFFFFFFFULL>
using double_one = brigand::double_<0x3FF0000000000000ULL>
using double_zero = brigand::double_<0x0000000000000000ULL>
using single_nan = brigand::single_<0xFFFFFFFFU>
using single_one = brigand::single_<0x3F800000U>
using single_zero = brigand::single_<0x00000000U>
Function Documentation
template<typename T > bool is_nan (T v)
Referenced by real_test().
void real_test ()
References is_nan().
Referenced by main().