#pragma once

#include <brigand/append.hpp>
#include <brigand/apply.hpp>
#include <brigand/arithmetic.hpp>
#include <brigand/at.hpp>
#include <brigand/back.hpp>
#include <brigand/bool.hpp>
#include <brigand/comparisons.hpp>
#include <brigand/count.hpp>
#include <brigand/for_each.hpp>
#include <brigand/for_each_args.hpp>
#include <brigand/front.hpp>
#include <brigand/identity.hpp>
#include <brigand/list.hpp>
#include <brigand/logical.hpp>
#include <brigand/size.hpp>
#include <brigand/transform.hpp>
#include <brigand/adapted/pair.hpp>
#include <brigand/adapted/tuple.hpp>
#include <brigand/adapted/variant.hpp>
